
## Executive Summary {-}

The purpose of the Lower Nicola River Watershed Connectivity Restoration Plan (WCRP) is to improve understanding of habitat connectivity for Chinook Salmon (Onchorhunchus tschawystcha), Coho Salmon (O. kisutch) and steelhead (O. mykiss) (herein referred to as Pacific salmon and steelhead) in the Lower Nicola River watershed and inform efforts to close knowledge gaps and plan and prioritize restoration. The lands and waters that form the basis of this plan are the traditional unceded territory of the Nlaka’pamux/Scw'exmx and Syilx peoples. 

Local data and knowledge are combined with connectivity modelling to estimate current connectivity status and identify structures that potentially block the most habitat. This informs the prioritization of field assessments to close the most significant knowledge gaps efficiently. Information from field assessments of barrier status and habitat condition are incorporated into the model, improving understanding of which barriers block the most habitat, and informing restoration prioritization. As knowledge gaps are closed and barriers are addressed, this plan will be revised to summarize progress and provide updated estimates of connectivity status and the status and relative importance of remaining structures. 

In the Lower Nicola River watershed, X km of spawning habitat are currently connected to the ocean and X km are disconnected from it. This means that X% of the X km of total habitat is connected. X km of rearing habitat are currently connected to the ocean and X km are disconnected from it. This means that X% of the X km of total habitat is connected. 

In the Lower Nicola River watershed, X structures potentially disconnect spawning habitat. Of these, X are identified as barriers in need of rehabilitation (priority barriers), X are identified as barriers that do not warrant rehabilitation (non-actionable), and X require further field assessment. X structures potentially disconnect rearing habitat. Of these, X are identified as barriers in need of rehabilitation (priority barriers), X are identified as barriers that do not warrant rehabilitation (non-actionable), and X require further field assessment. 

Figure 1: Map of spawning habitat and structures that are confirmed or potential barriers to fish passage in the Lower Nicola River watershed as of May 2026. Structure data were obtained from BCFishPass and the Canadian Aquatic Barriers Database (aquaticbarriers.ca). The accessibility model represents areas of the watershed that one or more species of Pacific salmon and steelhead could access naturally in the absence of anthropogenic barriers. The habitat model represents the subset of accessible waterbodies that may be used by one or more species of Pacific salmon and steelhead for spawning or rearing. Available local knowledge and data were incorporated and overruled habitat model results. Thick red lines represent habitat considered to be fully disconnected (upstream of barriers or unassessed structures). Barriers that were rehabilitated through implementation of this plan are shown, but other excluded structures (e.g., those found to be passable) are not. 

Figure 2: Map of rearing habitat and structures that are confirmed or potential barriers to fish passage in the Lower Nicola River watershed as of May 2026. Structure data were obtained from BCFishPass and the Canadian Aquatic Barriers Database (aquaticbarriers.ca). The accessibility model represents areas of the watershed that one or more species of Pacific salmon and steelhead could access naturally in the absence of anthropogenic barriers. The habitat model represents the subset of accessible waterbodies that may be used by one or more species of Pacific salmon and steelhead for spawning or rearing. Available local knowledge and data were incorporated and overruled habitat model results. Thick red lines represent habitat considered to be fully disconnected (upstream of barriers or unassessed structures). Barriers that were rehabilitated through implementation of this plan are shown, but other excluded structures (e.g., those found to be passable) are not. 

Figure 3: Habitat Accumulation Curve (HAC) showing structures in the Lower Nicola River watershed as of May 2026. Structures are ranked based on how much (km) of habitat for Pacific salmon and steelhead is upstream. The y-axis represents the cumulative amount of potential habitat gain (km). Sets of structures are indicated by a grey line below the curve, indicating that gains from addressing the downstream structure alone would be less than the combined gains from addressing all structures in the set. Habitat upstream of unassessed structures is considered disconnected until field assessments are completed. Structures that were excluded as passable are not shown; however, rehabilitated barriers are shown to demonstrate the connectivity gains achieved through implementation of this plan.  

This WCRP was initiated in 2020 with a series of workshops completed with local partners and rightsholders, and the first version of this WCRP was published in 2021. Since inception, the passability of X structures has been assessed, and further habitat assessments were completed at X of these. Fish passage has been rehabilitated at X barriers: Skuhun Creek mouth and Highway 8 crossings, Clapperton Creek dam, and Murray Lake Creek at Maka-Murray/Maka-Michael FSR junction. This has resulted in improved or restored access to X km of habitat. Some lateral habitat and thermal refugia investigations were also completed as part of this WCRP process; however, other groups active in the Lower Nicola have both pioneered and advanced this work beyond what was completed and reported upon here.  