# Appendix B – Partners and Detailed Methods  {-}

## Partners   {-}

```{r echo = FALSE}
#| label: table-13
#| tbl-cap: "Table 13: Lower Nicola River WCRP Planning Team members. Planning Team members contributed to the development of this plan by participating in scoping and planning meetings, and reviewing documents and data."
#| warning: false
source("Rscripts/table_formatting.R")
data <- read.csv("data/table13.csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```

```{r echo = FALSE}
#| label: table-14
#| tbl-cap: "Table 14: Lower Nicola River WCRP Planning Team members. Planning Team members contributed to the development of this plan by participating in scoping and planning meetings, and reviewing documents and data."
#| warning: false
source("Rscripts/table_formatting.R")
data <- read.csv("data/table14.csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```

## Detailed Methods {-}

For details about accessibility, habitat, or connectivity models including structure-ranking methods, see detailed documentation for BCFishPass here:[NSFishPass GitHub](https://github.com/Canadian-Wildlife-Federation/bcfishpass)