# Appendix A – Status of Structures Assessed in the Field {-}

## Non-Actionable Barriers
```{r table10, echo = FALSE, results = 'asis'}
#| label: table-10
#| tbl-cap: "Table 10: Structures in Lower Nicola River watershed that are confirmed as barriers to fish passage for Pacific salmon and steelhead as of May 2026 but have been identified by the Planning Team as non-actionable due to either logistic considerations (e.g., financial costs) or low-quality upstream habitat."
#| warning: false
#| echo: false
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/table10.csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```


## Data-deficient Barriers {-}

```{r table11, echo = FALSE, results = 'asis'}
#| label: table-11
#| tbl-cap: "Table 11: Structures in Lower Nicola River watershed that have been assessed for fish passage for Pacific salmon and steelhead as of May 2026, but either require an additional in-depth fish-passage assessment to confirm the passability status or a habitat assessment to confirm upstream habitat values."
#| warning: false
#| echo: false
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/table11.csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```


## Excluded Structures {-}

```{r table12, echo = FALSE, results = 'asis'}
#| label: table-12
#| tbl-cap: "Table 12: Structures in Lower Nicola River watershed that are excluded from further consideration in subsequent ranking and work planning because the structure is not present, is confirmed passable (e.g., bridge), or has no habitat upstream for Pacific salmon or steelhead."
#| warning: false
#| echo: false
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/table12.csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```

