```{python echo=FALSE}
import python.api_calls as api
import pandas as pd
import warnings
import python.connectivity_assess as conn_table

warnings.filterwarnings('ignore')
```

```{r}
#| echo: false
#| warning: false

library(reticulate)
api <- import("python.api_calls")
gain <- api$gain
gain_rear <- api$gain_rear

source("Rscripts/table_formatting.R")

```

# Connectivity Status and Ranking

## Current Connectivity Status {-}

```{python echo=FALSE}
#| label: tbl-table16
#| tbl-cap: "Rearing habitat connectivity gain requirements to meet WCRP goals in the Lower Nicola River watershed. The measures of currently accessible and total habitat values are derived from the intrinsic potential habitat model"
#| warning: false
#| echo: false

# Variables to API calls
connect = api.watershed_connectivity("ALL")[0]
total = round(api.watershed_connectivity("ALL")[1],2) 
access = round(api.watershed_connectivity("ALL")[2],2)
gain = round((total*0.96)-access,2)

# Data frame with table info
df = pd.DataFrame({"Habitat Type":["Spawning and Rearing"],
                   "Currently connected (km)":[str(access)],
                   "Total (km)": [str(total)],
                   "Current Connectivity Status":[str(connect)+"%"],
                   "Goal": ["90%"],
                   "Gain required (km)": [str(gain)]
                   })
                   
# Apply table styling
styled_df = df.style.hide().set_properties(**{'text-align': 'left'})
# header styling
table_styles = [{
       'selector': 'th',
       'props': [('background-color', '#008270'),('text-align', 'left')]
   }]
styled_df.set_table_styles(table_styles)

```

```{python echo=FALSE}
#| warning: false
#| echo: false

#| label: tbl-connectivity
#| tbl-cap: "Connectivity status assessment for thermal refuge (a), spawning (b), and rearing (c) habitat in the Lower Nicola River watershed. The Accessible Spawning Habitat and Accessible Rearing Habitat KEAs are evaluated by dividing the length of linear habitat (of each type) that is currently accessible to focal species by the total length of all linear habitat (of each type) in the watershed."
#| warning: false
#| echo: false

df = conn_table.make_assess_table("Anadromous salmonids", "Available off-channel Thermal Refuge", "Total Area (m2) of thermal refuge accessible", "?", " ?", "? ", api.connect)
df


```
**Comments:** No baseline data exists on the extent of overwintering habitat in the watershed. A priority action is included in the Operational Plan (strategy 2.3) to develop a habitat layer, and this will be used to inform this connectivity status assessment in the future.

```{python echo=FALSE}
#| warning: false
#| echo: false
df = conn_table.make_assess_table("Anadromous salmonids", "Available Spawning Habitat", "% of total linear spawning habitat accessible", 25, 50, 75, api.connect_spawn)
df

```
**Comments:** Indicator rating definitions are based on the consensus decisions of the planning team, including the decision not to define Fair. The current status is based on the connectivity model output, which is current as of December 2024.

```{python echo=FALSE}

df = conn_table.make_assess_table("Anadromous salmonids", "Available Rearing Habitat", "% of total linear rearing habitat accessible", 25, 50, 75, api.connect_rear)
df

```
**Comments:** Indicator rating definitions are based on the consensus decisions of the planning team, including the decision not to define Fair. The current status is based on the connectivity model output, which is current as of December 2024.


```{python echo=FALSE}
#| label: tbl-goals
#| tbl-cap: "Goals to improve (1) off-channel thermal refuge, (2) spawning, and (3) rearing habitat connectivity for focal species in the Lower Nicola River watershed over the lifespan of the WCRP (2021-2031). The goals were established through discussions with the planning team and represent the resulting desired state of connectivity in the watershed. The goals are subject to change as more information and data are collected over the course of the plan timeline (e.g., the current connectivity status is updated based on barrier field assessments)."
#| warning: false
#| echo: false

df = pd.DataFrame({"Goal #": [1,2,3],
                   "Goal": ["By 2031, the total area of groundwater-serviced off-channel thermal refuge accessible to anadromous salmonids will increase by 6,000 m2 within the Lower Nicola River watershed. ",
                            "By 2025, the % of total linear spawning habitat accessible to anadromous salmonids will not decrease below "+str(api.connect_spawn)+"% within the Lower Nicola River watershed.  ",
                            "By 2031, the % of total linear rearing habitat accessible to anadromous salmonids will increase from "+str(api.connect_rear)+"% to 90% within the Lower Nicola River watershed." ]
                    })

data = df.style.hide().set_properties(**{'text-align': 'left'})

data.set_table_styles(
   [{
       'selector': 'th',
       'props': [('background-color', '#008270'),('text-align', 'left')]
   }])

```
## Ranked Structures Table {.unnumbered}

```{python echo=FALSE}
#| label: tbl-ranked
#| tbl-cap: "Ranked Structures List"
#| warning: false
#| echo: false

df = api.GetTrackingTableData()

tableColumns = ['barrier_id','internal_name','structure_list_status','rank_total_upstr_hab','avg_gain_per_barrier','priority', 'next_steps', 'include_in_hac']


filtered_df = (
    df
      .loc[
          df['include_in_hac'] == 'yes',
          tableColumns
      ]
      .sort_values('avg_gain_per_barrier', ascending=False)
)

display_df = filtered_df.rename(columns={
    'barrier_id': 'Barrier ID',
    'internal_name': 'Site Name',
    'structure_list_status': 'Structure Status',
    'rank_total_upstr_hab': 'Upstream Habitat Rank',
    'avg_gain_per_barrier': 'Avg Habitat Gain',
    'priority': 'Priority',
    'next_steps': 'Next Steps',
    'include_in_hac': 'HAC'
})


data = display_df.style.hide().set_properties(**{'text-align': 'left'})

data.set_table_styles(
   [{
       'selector': 'th',
       'props': [('background-color', '#008270'),('text-align', 'left')]
   }])



```
## Habitat Accumulation Curve {.unnumbered}

![Figure 1: Habitat Accumulation Curve (HAC) showing structures in the Lower Nicola watershed as of x date. Structures are ranked based on how much (km) habitat is upstream to the next structure or set of structures and that would be reconnected if the structure(s) became passable. Sets of structures are indicated by a grey line below the curve, indicating that gains from addressing the downstream structure alone would be less than the combined gains from addressing all structures in the set. Habitat upstream of data-deficient structures is considered disconnected until field assessments are completed. Structures that were excluded as passable are not shown; however, rehabilitated barriers are shown to demonstrate the connectivity gains achieved through implementation of this plan. ](images/hac-lnic-test.png){fig-align="left"}

## Map {.unnumbered}

![Map of focal species habitat and structures that are confirmed or potential barriers to fish passage in the Lower Nicola watershed as of x date. Structure data were obtained from the Canadian Aquatic Barriers Database (aquaticbarriers.ca). The accessibility model represents areas of the watershed that focal species could access naturally in the absence of anthropogenic barriers. The habitat model represents the subset of accessible areas that may be used by focal species for key habitat function(s). Available local knowledge and data were incorporated and overrule habitat model results. Thick light-blue lines represent habitat that is currently connected, whereas thick red lines represent habitat considered to be disconnected because it is upstream of confirmed barriers or data-deficient structures. The y-axis represents the amount of habitat (km) blocked by each structure, discounted by 50% for first-order streams, and by passability (25%, 50%, 0r 75%) of partial barriers.  Barriers that were rehabilitated through implementation of this plan are shown, but other excluded structures (e.g., those found to be passable) are not.](images/hac-map-lnic.png)