# Data Download and Methods {-}


## Connectivity Status Assessment Methods {-}

The connectivity status assessment for anadromous salmonids in the Lower Nicola River watershed builds on existing connectivity modelling work undertaken by the BC Fish Passage Technical Working Group, resulting in a flexible, customizable open-source spatial model called "bcfishpass". The model spatially locates known and modelled barriers to fish passage, identifies potential spawning and rearing habitat for target species, and estimates the amount of habitat that is currently accessible to target species. The model uses an adapted version of the intrinsic potential (IP) fish habitat modelling framework (see @Sheer2009-kb for an overview of the IP framework). The habitat model uses two geomorphic characteristics of the stream network — channel gradient and mean annual discharge — to identify potential spawning habitat and rearing habitat for each target species. The habitat model does not attempt to definitively map each habitat type nor estimate habitat quality, but rather identifies stream segments that have high potential to support spawning or rearing habitat for each species based on the geomorphic characteristics of the segment. For more details on the connectivity and habitat model structure and parameters, see @Mazany-Wright2021-rz. The variables and thresholds used to model potential spawning and rearing habitat for each target species are summarized in @tbl-param. The quantity of modelled habitat for each species was aggregated for each habitat type to inform two of the KEAs — Accessible Spawning Habitat and Accessible Rearing Habitat — and represents a linear measure of potential habitat. To recognize the rearing value provided by features represented by polygons for certain species (e.g., wetlands for Coho Salmon) a multiplier of 1.5x the length of the stream segments flowing through the polygons was applied. 

```{r params, echo = FALSE, results = 'asis'}
#| label: tbl-param
#| tbl-cap: "Parameters and thresholds used to inform the intrinsic potential habitat model for spawning and rearing habitat for each target species in the Lower Nicola River watershed."
#| warning: false

library("flextable")

data <- read.csv("data/additional-params.csv", check.names=FALSE)
ft <- flextable(data)
ft <- bg(ft, bg = "#008270", part = "header")
ft <- color(ft, color = "white", part = "header")
ft <- set_caption(ft)
ft <- width(ft, width = 0.8)
ft 
```



