
# Acknowledgements and References {-}

## Recommended Citation 

N. Mazany-Wright, R. E. Bailey, S. M. Norris, J. Noseworthy, B. Rebellato, S. Sra, F. Montgomery, and N. W. R. Lapointe. 2026. Lower Nicola River watershed connectivity restoration plan. Canadian Wildlife Federation. Ottawa, Ontario, Canada. 


## Acknowledgements {-}

This plan is the culmination of a collaborative planning process undertaken in the Lower Nicola River watershed with a multi-partner Planning Team of individuals and groups passionate about the conservation and restoration of freshwater ecosystems and the species they support. Plan development was funded by the B. C. Salmon Restoration and Innovation Fund, Canada Nature Fund for Aquatic Species at Risk, and the RBC Bluewater Project. We were fortunate to benefit from the feedback, guidance, and wisdom of many groups and individuals who volunteered their time throughout this process — this publication would not have been possible without the engagement of our partners and the Planning Team (Appendix B).  

The Canadian Wildlife Federation recognizes that the lands and waters that form the basis of this plan are the traditional unceded territory of the Nlaka’pamux/Scw'exmx and Syilx peoples. We are grateful for the opportunity to learn from the stewards of this land and work together to benefit Pacific salmon and steelhead. A special thank you to the Lower Nicola Indian Band for sharing the traditional Nłeʔkepmxcín (Nlaka’pamuxcin) names used in this plan.  

We recognize the incredibly rich history of fish and fish habitat conservation and restoration work that has occurred in the Lower Nicola River watershed to date. A special thank you to Richard Bailey for providing background and contextual information on the myriad threats facing anadromous salmonid populations in the Lower Nicola. Thank you to Richard, Paul Mozin, Sarah Ostorforoff, and Tom Willms for identifying lateral barrier sites to assess during the 2021 field season. We are excited to continue partnering with local groups and organizations to build upon existing initiatives and provide a road map to push connectivity work forward over the next 10 years and beyond. Model outputs were further refined based on feedback provided by local knowledge holders beyond the Planning Team. Accessibility models were inspired by fish-passage prioritization approaches developed by British Columbia’s Fish Passage Technical Working Group.


## References {-}

Agrawal, A., R.S. Schick, E.P. Bjorkstedt, R.G. Szerlong, M.N. Goslin, B.C. Spence, T.H. Williams, and K.M. Burnett. 2005. Predicting the potential for historical Coho, Chinook, and Steelhead habitat in northern California. National Oceanic and Atmospheric Administration, NOAA-TM-NMFS-SWFSC-379.  

Bjornn, T.C., and D.W. Reiser. 1991. Habitat requirements of salmonids in streams. In Influences of Forest and Rangeland Management on Salmonid Fishes and their Habitats. American Fisheries Society Special Publication 19:83-138.  

Burnett, K.M., G.H. Reeves, D.J. Miller, S. Clarke, K. Vance-Borland, K. Christiansen. 2007. Distribution of salmon-habitat potential relative to landscape characteristics and implications for conservation. Ecological Applications 17(1):66-80.  

Busch, D.S., M. Sheer, K. Burnett, P. McElhany, and T. Cooney. 2011. Landscape-level model to predict spawning habitat for lower Columbia River fall Chinook Salmon (Oncorhynchus tshawytscha). River Research Applications 29(3):291-312.  

Coldwater Band. 2021. Our Nlaka'pamux History. https://www.coldwaterband.com/people-culture/history.  

Cooney, T., and D. Holzer. 2006. Appendix C: Interior Columbia basin stream type Chinook Salmon and Steelhead populations: habitat intrinsic potential analysis. National Oceanic and Atmospheric Administration, Northwest Fisheries Center.  

Committee on the Status of Endangered Wildlife in Canada. 2016. COSEWIC Assessment and Status Report on the Coho Salmon Oncorhynchus kisutch, Interior Fraser Population, in Canada. Committee on the Status of Endangered Wildlife in Canada. Ottawa. xi + 50 pp. (http://www.registrelep-sararegistry.gc.ca/default.asp?lang=en&n=24F7211B-1). 

Committee on the Status of Endangered Wildlife in Canada. 2020a. COSEWIC assessment and status report on the Chinook Salmon Oncorhynchus tshawytscha, Designatable Units in Southern British Columbia (Part Two – Designatable Units with High Levels of Artificial Releases in the Last 12 Years), in Canada. Committee on the Status of Endangered Wildlife in Canada. Ottawa. xxxv + 203 pp. (https://www.canada.ca/en/environmentclimate-change/services/species-risk-public-registry.html). 

Committee on the Status of Endangered Wildlife in Canada. 2020b. COSEWIC assessment and status report on the Steelhead Trout Oncorhynchus mykiss (Thompson River and Chilcotin River populations) in Canada. Committee on the Status of Endangered Wildlife in Canada. Ottawa. xvi + 104 pp. (https://www.canada.ca/en/environment-climatechange/services/species-risk-public-registry.html). 

Ecoscape Ltd. 2017. Nicola River Sensitive Habitat Inventory and Mapping and Aquatic Habitat Index. Prepared for Fraser Basic Council on behalf of Habitat Stewardship Program.  

[ESSA] ESSA Technologies Ltd. and Fraser Basin Council. 2019. Nicola Watershed Characterization - a Preliminary Evaluation of Watershed Issues and Priority Recommendations for the Nicola Forum. Report prepared by ESSA Technologies Ltd. and Fraser Basin Council for the Nicola Government to Government Forum, Merritt, BC.  

FINS Consulting Ltd. 2021. 2020 Fish passage barrier assessments in the Lower Nicola River watershed. Prepared for Canadian Wildlife Federation by FINS Consulting Ltd. Terrace, B. C.  

FINS Consulting Ltd. 2024. 2023 Fish passage assessment and habitat confirmation of select crossings in theLower Nicola River watershed group. Prepared for Canadian Wildlife Federation by FINS Consulting Ltd. Terrace, B. C. 

Fisheries and Oceans Canada. 1991. Fish Habitat Inventory and Information Program - Stream Summary Information. DFO. 

Fisheries and Oceans Canada. 2018. Recovery Potential Assessment for Chilcotin River and Thompson River Steelhead Trout (Oncorhynchus mykiss) Designatable Units. Science Advisory Report. 

Fraser Basin Council. n.d. Thomspon River Steelhead, Traditional Nlaka'pamux Fishing of the cóʕʷłeʔ. https://www.fraserbasin.bc.ca/_Library/TR/steelhead_nlakapamux_fishing_cfib_brochure.pdf.  

Lake, R.G. 1999. Activity and spawning behaviour in spawning Sockeye salmon. Thesis, University of British Columbia.  

LGL Ltd. 2007. Development of an Annual Salmonid Productivity Assessment Program for the Nicola River Watershed. Prepared for the Pacific Salmon Foundation.  

Lower Nicola Indian Band. 2015. Community Profile. http://lnib.net/wp-content/uploads/2015/07/LNIB-Community-Profile-Oct-2015.pdf.  

Lower Nicola Indian Band. 2025. 2024 fish passage culvert assessment, habitat confirmation, and verification of anadromous fish distribution. Prepared for Canadian Wildlife Federation by Lower Nicola Indian Band, Merritt, B. C.  

Lower Nicola Indian Band. 2025. 2024 fish habitat assessment and fish distribution assessments in the Lower Nicola watershed. Prepared for Canadian Wildlife Federation by Lower Nicola Indian Band, Merritt, B. C. 

Mazany-Wright, N., S. M. Norris, N. W. R. Lapointe, and B. Rebellato. 2021a. A Freshwater Connectivity Modelling Framework to Support Barrier Prioritization and Remediation in British Columbia. Canadian Wildlife Federation, Ottawa, Ontario.  

Mazany-Wright, N., S. M. Norris, N. W. R. Lapointe, and B. Rebellato. 2021b. B.C. Fish Passage Restoration Initiative Target Watershed Selection Process: Technical Documentation. Canadian Wildlife Federation, Ottawa, Ontario.  

Mazany-Wright, N., J. Noseworthy, S. Sra, S. M. Norris, and N. W. R Lapointe. 2021c. Breaking Down Barriers: a Practitioners' Guide to Watershed Connectivity Remediation Planning. Canadian Wildlife Federation, Ottawa, Ontario.  

McMahon, T.E. 1983. Habitat Suitability Index Models: Coho Salmon. U.S. Department of the Interior, Fish and Wildlife Service. FWS/OBS-82/10.49.  

Mozin, P. 2021. Fish Passage Barrier Assessments and Habitat Confirmations at Stream Crossings in the Lower Nicola River Watershed. Prepared for Canadian Wildlife Federation by Scw’exmx Tribal Council, Merritt, B. C.  

Neuman H.R., and C.P. Newcombe. 1977. Minimum acceptable stream flows in British Columbia: a review. Fisheries Management Report No. 70.  

Pacific Salmon Foundation. 2025. Methods for Assessing Status and Trends in Pacific Salmon Conservation Units and their Freshwater Habitats. The Pacific Salmon Foundation, Vancouver BC, Canada. Version 13. Available at https://salmonwatersheds.ca/document/lib_475/ 

Porter, M., D. Pickard, K. Wieckowski, and K. Bryan. 2008. Developing Fish Habitat Models for Broad-Scale Forest Planning in the Southern Interior of B.C. ESSA Technologies Ltd. and B.C. Ministry of Environment.  

Raleigh, R.F., and W.J. Miller. 1986. Habitat Suitability Index Models and Instream Flow Suitability Curves: Chinook Salmon. U.S. Fish and Wildlife Service Biological Reports 82(10.112).  

Roberge, M., J.B.M. Hume, C.K. Minns, and T. Slaney. 2002. Life history characteristics of freshwater fishes occurring in British Columbia and the Yukon, with major emphasis on stream habitat characteristics. Fisheries and Oceans Canada, Marine Environment and Habitat Science Division, Cultus Lake, British Columbia.  

Rosenfeld, J., M. Porter, and E. Parkinson. 2000. Habitat factors affecting the abundance and distribution of juvenile cutthroat trout (Oncorhynchus clarkii) and coho salmon (Oncorhynchus kisutch). Canadian Journal of Fisheries and Aquatic Sciences 57:766-774.  

Schindler, D.E., P.R. Leavitt, C. Brock, S.P. Johnson, and P.D. Quay. 2003. The importance of marine-derived nutrients to lake productivity and salmon population dynamics over the last five centuries in southwest Alaska. Presentation at the 2003 Annual Meeting, The Geological Society of America.  

Seliger, C., and B. Zeiringer. 2018. River connectivity, habitat fragmentation and related restoration measures. In Riverine Ecosystem Management: Science for Governing Towards a Sustainable Future, edited by Stefan Schmutz and Jan Sendzimir, 171–86. Cham: Springer International Publishing. https://doi.org/10.1007/978-3-319-73250-3_9. LOWER NICOLA RIVER WCRP: 2021-2031 41  

Sheer, M.B., D.S. Busch, E. Gilbert, J.M. Bayer, S. Lanigan, J.L. Schei, K.M. Burnett, and D. Miller. 2009. Development and management of fish intrinsic potential data and methodologies: State of the IP 2008 summary report. Pacific Northwest Aquatic Monitoring Partnership Series 2009-4.  

Sheer, M.B., and E.A. Steel. 2006. Lost watersheds: barriers, aquatic habitat connectivity, and salmon persistence in the Willamette and Lower Columbia basins. Transactions of the American Fisheries Society 135:1654-1669.  

Sloat M.R., G.H. Reeves, and K.R. Christiansen. 2017. Stream network geomorphology mediates predicted vulnerability of anadromous fish habitat fish habitat to hydrologic change in southeast Alaska. Global Change Biology 23:604-620.  

Upper Nicola Band. 2021. About Upper Nicola Band. https://uppernicola.com/ 

Woll, C., D. Albert, and D. Whited. 2017. A Preliminary Classification and Mapping of Salmon Ecological Systems in the Nushagak and Kvichak Watersheds, Alaska. The Nature Conservancy. 
